<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-practice/blob/main/01_Numpy_Arrays_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
# Fundamental library for numerical computing in Python

In [33]:
# Creation: arange generates values within a given interval
# Syntax: np.arange(start, stop, step)
a = np.arange(1, 21, 2)
display(a)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
# Vectorization: Applying operations to the whole array without explicit loops
b = a**2  # Calculates the square of every element
display(b)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [35]:
# linspace: Generates 'num' evenly spaced samples over a closed interval [start, stop]
arr = np.linspace(1, 10, 4)
display(arr)

array([ 1.,  4.,  7., 10.])

In [36]:
# logspace: Returns numbers spaced evenly on a log scale
# Below creates 3 numbers between 10^1 and 10^2
np.logspace(1, 2, 3)

array([ 10.       ,  31.6227766, 100.       ])

In [37]:
# Pre-allocation: Creating arrays filled with zeros
# Useful for initializing weights or placeholders
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [8]:
np.ones([2,2,4],dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [9]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [10]:
arr=np.full([3,3],6)
arr

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [11]:
b=np.empty([2,3])
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.random.rand(10)

array([0.7733523 , 0.51624184, 0.23652042, 0.79697587, 0.91831804,
       0.78761376, 0.98522706, 0.64220049, 0.89795998, 0.49711582])

In [13]:
np.random.rand(2,3)

array([[0.86557701, 0.24526082, 0.42129128],
       [0.3629188 , 0.87185366, 0.44896454]])

In [14]:
np.random.randn(3,3)#random floats from standard deviation average =0 and std=1

array([[-0.23905131, -0.58667365, -1.58962087],
       [ 0.14040955,  0.97025402,  0.18600708],
       [ 0.0043179 ,  2.09569223,  0.3954869 ]])

In [38]:
# Random Integers: Generates random integers from low (inclusive) to high (exclusive)
# Syntax: np.random.randint(low, high, size)
np.random.randint(1, 100, 7)

array([ 6, 65, 71, 28, 85, 65, 55])

In [16]:
np.random.randint(1,100,(3,4))  #start,stop,size/dimension

array([[15, 16, 58, 74],
       [36, 93, 75, 96],
       [30, 81, 52,  4]])

## 1. Array Creation & Sequences
Exploring different ways to initialize NumPy arrays.

In [17]:
list=[1,2,3,"MAnoj"]
arr=np.array(list)
arr

array(['1', '2', '3', 'MAnoj'], dtype='<U21')

In [18]:
a=np.array([1,2,3.1,3,"5"],dtype=str)       #dtype converts the list into given datatype
a

array(['1', '2', '3.1', '3', '5'], dtype='<U3')

In [19]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [20]:
new_arr=arr.astype(np.float64)
new_arr

array([1., 2., 3., 4., 5.])

In [21]:
arr2=new_arr.astype(np.str_)
arr2

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

In [22]:
# Type casting errors
a=np.array(["1","2",'Hello'])
a
# a.astype(np.int64) it'll give an error it can't convert hello into integer

array(['1', '2', 'Hello'], dtype='<U5')

In [39]:
## 2. Array Attributes
# Understanding the metadata of an array object
new = np.array([[1, 2, 3], [4, 5, 6]])
display(new)

print(f"Dimensions (ndim): {new.ndim}")
print(f"Shape (rows, cols): {new.shape}")
print(f"Total elements (size): {new.size}")
print(f"Memory per element (bytes): {new.itemsize}")
print(f"Total memory (bytes): {new.nbytes}")

array([[1, 2, 3],
       [4, 5, 6]])

Dimensions (ndim): 2
Shape (rows, cols): (2, 3)
Total elements (size): 6
Memory per element (bytes): 8
Total memory (bytes): 48


In [24]:
new.ndim

2

In [25]:
new.shape

(2, 3)

In [26]:
new.size

6

In [27]:
new.itemsize

8

In [28]:
new.itemsize*new.size

48