<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-practice/blob/main/01_Numpy_Arrays_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np

In [33]:
# Creation: arange generates values within a given interval
# Syntax: np.arange(start, stop, step)
a = np.arange(1, 21, 2)
display(a)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
# Vectorization: Applying operations to the whole array without explicit loops
b = a**2  # Calculates the square of every element
display(b)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [35]:
# linspace: Generates 'num' evenly spaced samples over a closed interval [start, stop]
arr = np.linspace(1, 10, 4)
display(arr)

array([ 1.,  4.,  7., 10.])

In [36]:
# logspace: Returns numbers spaced evenly on a log scale
# Below creates 3 numbers between 10^1 and 10^2
np.logspace(1, 2, 3)

array([ 10.       ,  31.6227766, 100.       ])

In [37]:
# Pre-allocation: Creating arrays filled with zeros
# Useful for initializing weights or placeholders
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
## 2. Pre-allocated Arrays
# Create an array of shape [2, 2] filled with 1.0 (float by default)
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [58]:
# Specifying dtype: Useful for saving memory when precision isn't required
np.ones([2, 2, 4], dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [59]:
# np.full: Useful for initializing a bias vector or constant filters
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [43]:
# Create a 3x3 matrix filled with the number 6
arr = np.full([3, 3], 6)
display(arr)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [60]:
# np.empty: Allocates memory without initializing, making it the fastest option for pre-allocation
b = np.empty([2, 3])
display(b)

array([[0.89772057, 0.73004485, 0.92664642],
       [0.21345132, 0.59349163, 0.61903013]])

In [45]:
## 3. Random Sampling
# rand: Generates 10 values from a uniform distribution between [0, 1)
np.random.rand(10)

array([0.30478267, 0.04590244, 0.25428598, 0.19971973, 0.11661961,
       0.25010186, 0.60880537, 0.0593583 , 0.69555743, 0.27027041])

In [50]:
# 2x3 matrix of random floats from a uniform distribution
np.random.rand(2, 3)

array([[0.89772057, 0.73004485, 0.92664642],
       [0.21345132, 0.59349163, 0.61903013]])

In [46]:
# randn: Samples from the Standard Normal Distribution (mean=0, std=1)
np.random.randn(3, 3)

array([[ 0.04940303, -0.93084481, -0.11015952],
       [-1.5745122 ,  0.19927621,  0.7854869 ],
       [-0.68240684,  0.60847344, -0.64516608]])

In [38]:
# Random Integers: Generates random integers from low (inclusive) to high (exclusive)
# Syntax: np.random.randint(low, high, size)
np.random.randint(1, 100, 7)

array([ 6, 65, 71, 28, 85, 65, 55])

In [47]:
# randint: Random integers in range [1, 100) with a 3x4 shape
np.random.randint(1, 100, (3, 4))

array([[24, 65, 31, 36],
       [98, 35, 86, 72],
       [92, 34, 46, 15]])

## 1. Array Creation & Sequences
Exploring different ways to initialize NumPy arrays.

In [48]:
## 4. Data Types and Casting
# Note: NumPy arrays must have a single data type (homogeneity)
# Combining ints and strings results in 'Unicode' type (<U21)
my_list = [1, 2, 3, "MAnoj"]
arr = np.array(my_list)
display(arr)

array(['1', '2', '3', 'MAnoj'], dtype='<U21')

In [61]:
## 4. Data Types and Casting
# Explicit dtype conversion during array creation
a = np.array([1, 2, 3.1, 3, "5"], dtype=str)
display(a)

array(['1', '2', '3.1', '3', '5'], dtype='<U3')

In [19]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [49]:
# astype: Used for explicit type conversion
# Converting integer array to float for scientific calculations
arr_numeric = np.array([1, 2, 3, 4, 5])
new_arr = arr_numeric.astype(np.float64)
display(new_arr)

array([1., 2., 3., 4., 5.])

In [62]:
# String conversion: Useful for data cleaning and export preparations
arr2 = new_arr.astype(np.str_)
display(arr2)

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

In [51]:
# Type casting limitations
# Attempting to convert 'Hello' to an integer would raise a ValueError
a = np.array(["1", "2", "Hello"])
display(a)
# a.astype(np.int64)  # This line is commented out because it would fail

array(['1', '2', 'Hello'], dtype='<U5')

In [63]:
## 2. Array Attributes
# Understanding the metadata of an array object
new = np.array([[1, 2, 3], [4, 5, 6]])
display(new)

print(f"Dimensions (ndim): {new.ndim}")
print(f"Shape (rows, cols): {new.shape}")
print(f"Total elements (size): {new.size}")
print(f"Total memory (bytes): {new.nbytes}")

array([[1, 2, 3],
       [4, 5, 6]])

Dimensions (ndim): 2
Shape (rows, cols): (2, 3)
Total elements (size): 6
Total memory (bytes): 48


In [52]:
# ndim: Number of axes (dimensions) of the array
print(f"Number of dimensions: {new.ndim}")

Number of dimensions: 2


In [53]:
# shape: A tuple of integers indicating the size of the array in each dimension
print(f"Array shape: {new.shape}")

Array shape: (2, 3)


In [54]:
# size: Total number of elements in the array (rows * cols)
print(f"Total size: {new.size}")

Total size: 6


In [56]:
# Calculating total memory consumption manually
# total_bytes = itemsize * size
total_memory = new.itemsize * new.size
print(f"Manual memory calculation: {total_memory} bytes")

Manual memory calculation: 48 bytes
