<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-practice/blob/main/02_Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ar=np.array([1,2,3,4,5,6])
ar

array([1, 2, 3, 4, 5, 6])

In [3]:
arr=ar.reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a=arr.ravel()   #ravel array it changes the original array
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[0]=10
a
# arr

array([10,  2,  3,  4,  5,  6])

In [6]:
b=a.flatten()
b
               #flatten returns a copy of array

array([10,  2,  3,  4,  5,  6])

In [7]:
b[1]=96
b

array([10, 96,  3,  4,  5,  6])

In [8]:
arr

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

Arithmetic operations on Array

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [10]:
np.dot(a,b)   #multiplication of a and b

np.int64(32)

In [11]:
a@b         #multiplication of a and

np.int64(32)

In [12]:
a+b

array([5, 7, 9])

In [13]:
a-b

array([-3, -3, -3])

In [14]:
b%a

array([0, 1, 0])

In [15]:
a/b

array([0.25, 0.4 , 0.5 ])

In [16]:
b/a

array([4. , 2.5, 2. ])

In [17]:
b//a  #integer division values

array([4, 2, 2])

In [18]:
a*b

array([ 4, 10, 18])

In [19]:
a**2 , b**2 , a**b

(array([1, 4, 9]), array([16, 25, 36]), array([  1,  32, 729]))

Universal function -> Ufuncs

In [20]:
a=np.array([1,4,9,25])
np.sqrt(a)


array([1., 2., 3., 5.])

In [21]:
print(np.exp([1,2,9]))

[2.71828183e+00 7.38905610e+00 8.10308393e+03]


In [22]:
angle=np.array([0,30,90,np.pi/2,np.pi])
np.sin(angle)

array([ 0.00000000e+00, -9.88031624e-01,  8.93996664e-01,  1.00000000e+00,
        1.22464680e-16])

### 5. Stacking and Concatenation
Interviews often test how you combine datasets. `np.concatenate`, `np.vstack` (vertical), and `np.hstack` (horizontal) are key.

In [23]:
a=np.array([1,2,3])
b=np.array([4,5,6])                 #using concatenation
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [24]:
combine=np.concatenate([a,b])
combine

array([1, 2, 3, 4, 5, 6])

In [25]:
a = np.array([[1, 2, 3],["P","q","r"]])
b = np.array([[4, 5, 6],[9,0,8]])

print("Horizontal Stack:", np.hstack((a, b)))
print("Vertical Stack:\n", np.vstack((a, b)))
print(np.stack((a,b),axis=1))

Horizontal Stack: [['1' '2' '3' '4' '5' '6']
 ['P' 'q' 'r' '9' '0' '8']]
Vertical Stack:
 [['1' '2' '3']
 ['P' 'q' 'r']
 ['4' '5' '6']
 ['9' '0' '8']]
[[['1' '2' '3']
  ['4' '5' '6']]

 [['P' 'q' 'r']
  ['9' '0' '8']]]


In [26]:
a=np.array([1,2,3,4,5])

In [27]:
a[::-1]

array([5, 4, 3, 2, 1])

In [28]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [29]:
matrix[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matrix[1:2,1:2]

array([[5]])

In [31]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [32]:
a = np.array([1,2,3,4,7,5,6,7])
v=[1,2,4,5]
np.take(a,v)

array([2, 3, 7, 5])

In [33]:
a = np.array([[1, 2, 3],[4,5,6]])

for v in np.nditer(a):
  print(v*2,end=" ")

2 4 6 8 10 12 

In [34]:
for ind,x in np.ndenumerate(a):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [35]:
ad=np.array([[1,2,3],[4,5,6],[7,8,9]])
ad

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ad.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])