<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-python-practice/blob/main/03_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
arr=np.array([1,5,8,0])
arr.repeat(3)  # or i can write like b = np.repat(arr,3)      b

array([1, 1, 1, 5, 5, 5, 8, 8, 8, 0, 0, 0])

In [9]:
# tile -> repeat the whole array
np.tile(arr,2)

array([1, 5, 8, 0, 1, 5, 8, 0])

In [10]:
#Aggregate Functions:
arr=np.array([1,5,6,9])
print(arr.sum())  # or np.sum(arr)

21


In [11]:
np.mean(arr,dtype=np.int64)

np.int64(5)

In [12]:
np.median(arr)

np.float64(5.5)

In [13]:
np.std(arr)

np.float64(2.8613807855648994)

In [14]:
np.var(arr)

np.float64(8.1875)

In [15]:
np.min(arr)

np.int64(1)

In [16]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.sum(matrix,axis=1)

array([ 6, 15, 24])

In [18]:
#cumulative  operations -> running total
a=np.array([1,2,3,4])
np.cumsum(a)

array([ 1,  3,  6, 10])

In [19]:
np.cumprod(a)

array([ 1,  2,  6, 24])

#conditional based choices

In [20]:
# where:
arr

array([1, 5, 6, 9])

In [21]:
np.where(arr>=6,"BIG","SMALL")

array(['SMALL', 'SMALL', 'BIG', 'BIG'], dtype='<U5')

In [22]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.where(matrix>=6,"True","False")

array([['False', 'False', 'False'],
       ['False', 'False', 'True'],
       ['True', 'True', 'True']], dtype='<U5')

In [24]:
np.argwhere(matrix>=6)

array([[1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [25]:
d=np.logical_and(matrix>=5,matrix<=8)
d

array([[False, False, False],
       [False,  True,  True],
       [ True,  True, False]])

In [26]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.logical_and(matrix>5,matrix<9)

array([[False, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [28]:
np.logical_or(matrix>5,matrix<9)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [29]:
np.logical_not(matrix>5,matrix<9)

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

#Broadcasting
it'll perform if there is a scalar shape or a common dimension in both arrays

In [58]:
image=np.array([[1,2,3],[4,5,6],[7,8,9]])
image

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a=image+50
a

array([[51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [60]:
image*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [64]:
vec=np.array([[1],[2],[3]])
image+vec

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

#Vectorization

In [65]:
def sq(a):
  return a+2*2

In [66]:
arr

array([1, 5, 6, 9])

In [67]:
v=np.vectorize(sq)
v(arr)

array([ 5,  9, 10, 13])

In [68]:
ar=np.array([1,2,np.nan,4,7,8,np.nan])
ar

array([ 1.,  2., nan,  4.,  7.,  8., nan])

In [69]:
np.isnan(ar)

array([False, False,  True, False, False, False,  True])

In [70]:
np.isinf(ar)

array([False, False, False, False, False, False, False])

In [71]:
np.isinf(ar)

array([False, False, False, False, False, False, False])

In [72]:
np.nan_to_num(ar)

array([1., 2., 0., 4., 7., 8., 0.])