<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-practice/blob/main/03_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,5,8,0])
arr.repeat(3)  # or i can write like b = np.repat(arr,3)      b

array([1, 1, 1, 5, 5, 5, 8, 8, 8, 0, 0, 0])

In [3]:
# tile -> repeat the whole array
np.tile(arr,2)

array([1, 5, 8, 0, 1, 5, 8, 0])

In [4]:
#Aggregate Functions:
arr=np.array([1,5,6,9])
print(arr.sum())  # or np.sum(arr)

21


In [5]:
np.mean(arr,dtype=np.int64)

np.int64(5)

In [6]:
np.median(arr)

np.float64(5.5)

In [7]:
np.std(arr)

np.float64(2.8613807855648994)

In [8]:
np.var(arr)

np.float64(8.1875)

In [9]:
np.min(arr)

np.int64(1)

In [10]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.sum(matrix,axis=1)

array([ 6, 15, 24])

In [12]:
#cumulative  operations -> running total
a=np.array([1,2,3,4])
np.cumsum(a)

array([ 1,  3,  6, 10])

In [13]:
np.cumprod(a)

array([ 1,  2,  6, 24])

#conditional based choices

In [14]:
# where:
arr

array([1, 5, 6, 9])

In [15]:
np.where(arr>=6,"BIG","SMALL")

array(['SMALL', 'SMALL', 'BIG', 'BIG'], dtype='<U5')

In [16]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.where(matrix>=6,"True","False")

array([['False', 'False', 'False'],
       ['False', 'False', 'True'],
       ['True', 'True', 'True']], dtype='<U5')

In [18]:
np.argwhere(matrix>=6)

array([[1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [19]:
d=np.logical_and(matrix>=5,matrix<=8)
d

array([[False, False, False],
       [False,  True,  True],
       [ True,  True, False]])

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.logical_and(matrix>5,matrix<9)

array([[False, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [22]:
np.logical_or(matrix>5,matrix<9)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [23]:
np.logical_not(matrix>5,matrix<9)

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

#Broadcasting
it'll perform if there is a scalar shape or a common dimension in both arrays

In [24]:
image=np.array([[0,2,3],[4,5,6],[7,8,9]])
image

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a=np.arange(3).reshape(1,3)
b=np.arange(3)
print(a)
print(b)
print(a+b)

[[0 1 2]]
[0 1 2]
[[0 2 4]]


In [44]:
a=np.arange(3).reshape(3,1)
b=np.arange(3)
print(a)
print(b)
print(a+b)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


When attempting to perform `a + b` with `a.shape = (1, 4)` and `b.shape = (3,)`, it will result in an error due to NumPy's broadcasting rules.

Here's why:

1.  **Dimension Alignment**: NumPy compares array shapes element-wise, starting from the trailing (rightmost) dimension.
    *   `a`: `(1, 4)`
    *   `b`: `(  3)` (internally, NumPy treats it as `(1, 3)` for comparison by padding with ones on the left if dimensions differ).

2.  **Compatibility Check**: For broadcasting to work, dimensions must either be equal, or one of them must be 1.
    *   **Rightmost dimension**: `4` (from `a`) vs `3` (from `b`). These are neither equal nor does one of them equal 1. Therefore, broadcasting fails.

To make these arrays broadcastable, you need to ensure their dimensions are compatible according to the rules. For instance, if you change `b` to have a shape of `(3, 1)`:
*   `a`: `(1, 4)`
*   `b`: `(3, 1)`

Now, comparing from right to left:
*   Rightmost dimension: `4` (from `a`) vs `1` (from `b`). `b`'s dimension `1` will stretch to `4`.
*   Next dimension: `1` (from `a`) vs `3` (from `b`). `a`'s dimension `1` will stretch to `3`.

The resulting broadcasted shape would be `(3, 4)`, and the operation would succeed.

In [50]:
a=np.arange(4).reshape(1,4)
b=np.arange(3).reshape(3)
print(a)
print(b)
# print(a+b)

[[0 1 2 3]]
[0 1 2]


In [38]:
image+50


array([[50, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [26]:
image*[1,2,3]

array([[ 0,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

#Vectorization

In [28]:
def sq(a):
  return a+2*2

In [29]:
arr

array([1, 5, 6, 9])

In [30]:
v=np.vectorize(sq)
v(arr)

array([ 5,  9, 10, 13])

In [31]:
ar=np.array([1,2,np.nan,4,7,8,np.nan])
ar

array([ 1.,  2., nan,  4.,  7.,  8., nan])

In [32]:
np.isnan(ar)

array([False, False,  True, False, False, False,  True])

In [33]:
np.isinf(ar)

array([False, False, False, False, False, False, False])

In [34]:
np.isinf(ar)

array([False, False, False, False, False, False, False])

In [35]:
np.nan_to_num(ar)

array([1., 2., 0., 4., 7., 8., 0.])

### Vectorization vs Loops
Vectorization allows you to perform batch operations without explicit `for` loops.

In [36]:
import time

# Large array for timing
large_arr = np.arange(1000000)

# Using a loop
start = time.time()
loop_result = [x + 5 for x in large_arr]
print(f"Loop time: {time.time() - start:.4f}s")

# Using vectorization
start = time.time()
vec_result = large_arr + 5
print(f"Vectorized time: {time.time() - start:.4f}s")

Loop time: 0.1650s
Vectorized time: 0.0033s


### Cosine Similarity Implementation
We can calculate cosine similarity using NumPy's dot product and linear algebra norm functions.

In [37]:
def cosine_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    return dot_product / (norm_v1 * norm_v2)

# Example vectors
vec_a = np.array([1, 2, 3])
vec_b = np.array([1, 2, 3])
vec_c = np.array([-1, -2, -3])

print(f"Similarity (same): {cosine_similarity(vec_a, vec_b):.2f}")
print(f"Similarity (opposite): {cosine_similarity(vec_a, vec_c):.2f}")

Similarity (same): 1.00
Similarity (opposite): -1.00
